export default
{
    "scene":{
        "background":"0x4f6f8f"
    },
    "ground":"./3d_models/ground.gltf",
    "node":"./3d_models/node.gltf",
    "mouse":{
        click_hold_delay_ms : 600
    },
    "control":{
        "file":"./3d_models/configurator.gltf",
        "name":"slider",
        "space_range":3,
        "screen_move_sensitivity":150.0,
        "is_bullet_centered_not_slider":true,
        "sliderPos_CamToObj_ratio":0.3,
        "sliderScale_ToObj_ratio":2
    },
    "stats":{
        "enabled_by_default":true
    },
    "effects":{
        "lights_toon_material":false,
        "outline":{
            "enabled":true,
            "show_gui":false,
            "visibleEdgeColor":"#004107",
            "hiddenEdgeColor":"#39160b"
        }
    }
}
